const MONGODBURL = process.env.MONGODB_URL;
const ACCESSTOKENSECRET = process.env.ACCESS_TOKEN_SECRET;
const REFRESHTOKENSECRET = process.env.REFRESH_TOKEN_SECRET;
const ACCESSTOKENEXPIRY = process.env.ACCESS_TOKEN_EXPIRY;
const REFRESHTOKENEXPIRY = process.env.REFRESH_TOKEN_EXPIRY;

module.exports = {
    MONGODBURL,
    ACCESSTOKENEXPIRY,
    REFRESHTOKENEXPIRY,
    ACCESSTOKENSECRET,
    REFRESHTOKENSECRET,
};
